#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phan_Mem_Quan_Ly_Cam_Do.DoiTuong
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Quan_Ly_Cam_Do")]
	public partial class DB_Quan_Ly_Cam_DoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHUNG_TU_CHI_TIET(CHUNG_TU_CHI_TIET instance);
    partial void UpdateCHUNG_TU_CHI_TIET(CHUNG_TU_CHI_TIET instance);
    partial void DeleteCHUNG_TU_CHI_TIET(CHUNG_TU_CHI_TIET instance);
    partial void InsertCHUNG_TU(CHUNG_TU instance);
    partial void UpdateCHUNG_TU(CHUNG_TU instance);
    partial void DeleteCHUNG_TU(CHUNG_TU instance);
    partial void InsertCHUNG_TU_THU_CHI(CHUNG_TU_THU_CHI instance);
    partial void UpdateCHUNG_TU_THU_CHI(CHUNG_TU_THU_CHI instance);
    partial void DeleteCHUNG_TU_THU_CHI(CHUNG_TU_THU_CHI instance);
    #endregion
		
		public DB_Quan_Ly_Cam_DoDataContext() : 
				base(global::Phan_Mem_Quan_Ly_Cam_Do.Properties.Settings.Default.Quan_Ly_Cam_DoConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DB_Quan_Ly_Cam_DoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_Quan_Ly_Cam_DoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_Quan_Ly_Cam_DoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_Quan_Ly_Cam_DoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHUNG_TU_CHI_TIET> CHUNG_TU_CHI_TIETs
		{
			get
			{
				return this.GetTable<CHUNG_TU_CHI_TIET>();
			}
		}
		
		public System.Data.Linq.Table<CHUNG_TU> CHUNG_TUs
		{
			get
			{
				return this.GetTable<CHUNG_TU>();
			}
		}
		
		public System.Data.Linq.Table<CHUNG_TU_THU_CHI> CHUNG_TU_THU_CHIs
		{
			get
			{
				return this.GetTable<CHUNG_TU_THU_CHI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUNG_TU_CHI_TIET")]
	public partial class CHUNG_TU_CHI_TIET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Ma_Chi_Tiet;
		
		private string _Ma_Chung_Tu;
		
		private string _Ten_Tai_San;
		
		private string _Loai_Vang;
		
		private string _Trong_Luong;
		
		private System.Nullable<decimal> _Trong_Luong_Vang_18k;
		
		private System.Nullable<decimal> _Trong_Luong_Vang_24k;
		
		private System.Nullable<decimal> _Trong_Luong_Khac;
		
		private string _Chuan_Do;
		
		private System.Nullable<decimal> _Gia_Tri_Vat_Cam;
		
		private System.Nullable<long> _Sap_Xep;
		
		private EntityRef<CHUNG_TU> _CHUNG_TU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Chi_TietChanging(System.Guid value);
    partial void OnMa_Chi_TietChanged();
    partial void OnMa_Chung_TuChanging(string value);
    partial void OnMa_Chung_TuChanged();
    partial void OnTen_Tai_SanChanging(string value);
    partial void OnTen_Tai_SanChanged();
    partial void OnLoai_VangChanging(string value);
    partial void OnLoai_VangChanged();
    partial void OnTrong_LuongChanging(string value);
    partial void OnTrong_LuongChanged();
    partial void OnTrong_Luong_Vang_18kChanging(System.Nullable<decimal> value);
    partial void OnTrong_Luong_Vang_18kChanged();
    partial void OnTrong_Luong_Vang_24kChanging(System.Nullable<decimal> value);
    partial void OnTrong_Luong_Vang_24kChanged();
    partial void OnTrong_Luong_KhacChanging(System.Nullable<decimal> value);
    partial void OnTrong_Luong_KhacChanged();
    partial void OnChuan_DoChanging(string value);
    partial void OnChuan_DoChanged();
    partial void OnGia_Tri_Vat_CamChanging(System.Nullable<decimal> value);
    partial void OnGia_Tri_Vat_CamChanged();
    partial void OnSap_XepChanging(System.Nullable<long> value);
    partial void OnSap_XepChanged();
    #endregion
		
		public CHUNG_TU_CHI_TIET()
		{
			this._CHUNG_TU = default(EntityRef<CHUNG_TU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Chi_Tiet", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Ma_Chi_Tiet
		{
			get
			{
				return this._Ma_Chi_Tiet;
			}
			set
			{
				if ((this._Ma_Chi_Tiet != value))
				{
					this.OnMa_Chi_TietChanging(value);
					this.SendPropertyChanging();
					this._Ma_Chi_Tiet = value;
					this.SendPropertyChanged("Ma_Chi_Tiet");
					this.OnMa_Chi_TietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Chung_Tu", DbType="NVarChar(250)")]
		public string Ma_Chung_Tu
		{
			get
			{
				return this._Ma_Chung_Tu;
			}
			set
			{
				if ((this._Ma_Chung_Tu != value))
				{
					if (this._CHUNG_TU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Chung_TuChanging(value);
					this.SendPropertyChanging();
					this._Ma_Chung_Tu = value;
					this.SendPropertyChanged("Ma_Chung_Tu");
					this.OnMa_Chung_TuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Tai_San", DbType="NVarChar(250)")]
		public string Ten_Tai_San
		{
			get
			{
				return this._Ten_Tai_San;
			}
			set
			{
				if ((this._Ten_Tai_San != value))
				{
					this.OnTen_Tai_SanChanging(value);
					this.SendPropertyChanging();
					this._Ten_Tai_San = value;
					this.SendPropertyChanged("Ten_Tai_San");
					this.OnTen_Tai_SanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai_Vang", DbType="NVarChar(250)")]
		public string Loai_Vang
		{
			get
			{
				return this._Loai_Vang;
			}
			set
			{
				if ((this._Loai_Vang != value))
				{
					this.OnLoai_VangChanging(value);
					this.SendPropertyChanging();
					this._Loai_Vang = value;
					this.SendPropertyChanged("Loai_Vang");
					this.OnLoai_VangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trong_Luong", DbType="NVarChar(250)")]
		public string Trong_Luong
		{
			get
			{
				return this._Trong_Luong;
			}
			set
			{
				if ((this._Trong_Luong != value))
				{
					this.OnTrong_LuongChanging(value);
					this.SendPropertyChanging();
					this._Trong_Luong = value;
					this.SendPropertyChanged("Trong_Luong");
					this.OnTrong_LuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trong_Luong_Vang_18k", DbType="Money")]
		public System.Nullable<decimal> Trong_Luong_Vang_18k
		{
			get
			{
				return this._Trong_Luong_Vang_18k;
			}
			set
			{
				if ((this._Trong_Luong_Vang_18k != value))
				{
					this.OnTrong_Luong_Vang_18kChanging(value);
					this.SendPropertyChanging();
					this._Trong_Luong_Vang_18k = value;
					this.SendPropertyChanged("Trong_Luong_Vang_18k");
					this.OnTrong_Luong_Vang_18kChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trong_Luong_Vang_24k", DbType="Money")]
		public System.Nullable<decimal> Trong_Luong_Vang_24k
		{
			get
			{
				return this._Trong_Luong_Vang_24k;
			}
			set
			{
				if ((this._Trong_Luong_Vang_24k != value))
				{
					this.OnTrong_Luong_Vang_24kChanging(value);
					this.SendPropertyChanging();
					this._Trong_Luong_Vang_24k = value;
					this.SendPropertyChanged("Trong_Luong_Vang_24k");
					this.OnTrong_Luong_Vang_24kChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trong_Luong_Khac", DbType="Money")]
		public System.Nullable<decimal> Trong_Luong_Khac
		{
			get
			{
				return this._Trong_Luong_Khac;
			}
			set
			{
				if ((this._Trong_Luong_Khac != value))
				{
					this.OnTrong_Luong_KhacChanging(value);
					this.SendPropertyChanging();
					this._Trong_Luong_Khac = value;
					this.SendPropertyChanged("Trong_Luong_Khac");
					this.OnTrong_Luong_KhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chuan_Do", DbType="NVarChar(250)")]
		public string Chuan_Do
		{
			get
			{
				return this._Chuan_Do;
			}
			set
			{
				if ((this._Chuan_Do != value))
				{
					this.OnChuan_DoChanging(value);
					this.SendPropertyChanging();
					this._Chuan_Do = value;
					this.SendPropertyChanged("Chuan_Do");
					this.OnChuan_DoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia_Tri_Vat_Cam", DbType="Money")]
		public System.Nullable<decimal> Gia_Tri_Vat_Cam
		{
			get
			{
				return this._Gia_Tri_Vat_Cam;
			}
			set
			{
				if ((this._Gia_Tri_Vat_Cam != value))
				{
					this.OnGia_Tri_Vat_CamChanging(value);
					this.SendPropertyChanging();
					this._Gia_Tri_Vat_Cam = value;
					this.SendPropertyChanged("Gia_Tri_Vat_Cam");
					this.OnGia_Tri_Vat_CamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sap_Xep", DbType="BigInt")]
		public System.Nullable<long> Sap_Xep
		{
			get
			{
				return this._Sap_Xep;
			}
			set
			{
				if ((this._Sap_Xep != value))
				{
					this.OnSap_XepChanging(value);
					this.SendPropertyChanging();
					this._Sap_Xep = value;
					this.SendPropertyChanged("Sap_Xep");
					this.OnSap_XepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUNG_TU_CHUNG_TU_CHI_TIET", Storage="_CHUNG_TU", ThisKey="Ma_Chung_Tu", OtherKey="Ma_Chung_Tu", IsForeignKey=true, DeleteRule="CASCADE")]
		public CHUNG_TU CHUNG_TU
		{
			get
			{
				return this._CHUNG_TU.Entity;
			}
			set
			{
				CHUNG_TU previousValue = this._CHUNG_TU.Entity;
				if (((previousValue != value) 
							|| (this._CHUNG_TU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUNG_TU.Entity = null;
						previousValue.CHUNG_TU_CHI_TIETs.Remove(this);
					}
					this._CHUNG_TU.Entity = value;
					if ((value != null))
					{
						value.CHUNG_TU_CHI_TIETs.Add(this);
						this._Ma_Chung_Tu = value.Ma_Chung_Tu;
					}
					else
					{
						this._Ma_Chung_Tu = default(string);
					}
					this.SendPropertyChanged("CHUNG_TU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUNG_TU")]
	public partial class CHUNG_TU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Chung_Tu;
		
		private string _So;
		
		private string _Lien;
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private string _Ten_Khach_Hang;
		
		private string _So_CMND;
		
		private string _Ngay_Cap_CMND;
		
		private string _Noi_Cap;
		
		private string _Ngay_Sinh;
		
		private string _Dia_Chi;
		
		private string _So_Dien_Thoai;
		
		private string _Chu_Tiem;
		
		private System.Nullable<decimal> _So_Tien_Cam;
		
		private string _Tu_Ngay;
		
		private string _Den_Ngay;
		
		private System.Nullable<decimal> _Lai_Suat_Ngay;
		
		private System.Nullable<decimal> _Lai_Suat_Thang;
		
		private string _Ghi_Chu;
		
		private System.Nullable<decimal> _Tien_Lai_Cu;
		
		private string _Chung_Tu_Goc;
		
		private System.Nullable<bool> _Da_Lam_Lai_Giay;
		
		private System.Nullable<bool> _Da_Chuoc;
		
		private System.Nullable<bool> _Mat_Giay;
		
		private System.Nullable<long> _Sap_Xep;
		
		private EntitySet<CHUNG_TU_CHI_TIET> _CHUNG_TU_CHI_TIETs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Chung_TuChanging(string value);
    partial void OnMa_Chung_TuChanged();
    partial void OnSoChanging(string value);
    partial void OnSoChanged();
    partial void OnLienChanging(string value);
    partial void OnLienChanged();
    partial void OnNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChanged();
    partial void OnTen_Khach_HangChanging(string value);
    partial void OnTen_Khach_HangChanged();
    partial void OnSo_CMNDChanging(string value);
    partial void OnSo_CMNDChanged();
    partial void OnNgay_Cap_CMNDChanging(string value);
    partial void OnNgay_Cap_CMNDChanged();
    partial void OnNoi_CapChanging(string value);
    partial void OnNoi_CapChanged();
    partial void OnNgay_SinhChanging(string value);
    partial void OnNgay_SinhChanged();
    partial void OnDia_ChiChanging(string value);
    partial void OnDia_ChiChanged();
    partial void OnSo_Dien_ThoaiChanging(string value);
    partial void OnSo_Dien_ThoaiChanged();
    partial void OnChu_TiemChanging(string value);
    partial void OnChu_TiemChanged();
    partial void OnSo_Tien_CamChanging(System.Nullable<decimal> value);
    partial void OnSo_Tien_CamChanged();
    partial void OnTu_NgayChanging(string value);
    partial void OnTu_NgayChanged();
    partial void OnDen_NgayChanging(string value);
    partial void OnDen_NgayChanged();
    partial void OnLai_Suat_NgayChanging(System.Nullable<decimal> value);
    partial void OnLai_Suat_NgayChanged();
    partial void OnLai_Suat_ThangChanging(System.Nullable<decimal> value);
    partial void OnLai_Suat_ThangChanged();
    partial void OnGhi_ChuChanging(string value);
    partial void OnGhi_ChuChanged();
    partial void OnTien_Lai_CuChanging(System.Nullable<decimal> value);
    partial void OnTien_Lai_CuChanged();
    partial void OnChung_Tu_GocChanging(string value);
    partial void OnChung_Tu_GocChanged();
    partial void OnDa_Lam_Lai_GiayChanging(System.Nullable<bool> value);
    partial void OnDa_Lam_Lai_GiayChanged();
    partial void OnDa_ChuocChanging(System.Nullable<bool> value);
    partial void OnDa_ChuocChanged();
    partial void OnMat_GiayChanging(System.Nullable<bool> value);
    partial void OnMat_GiayChanged();
    partial void OnSap_XepChanging(System.Nullable<long> value);
    partial void OnSap_XepChanged();
    #endregion
		
		public CHUNG_TU()
		{
			this._CHUNG_TU_CHI_TIETs = new EntitySet<CHUNG_TU_CHI_TIET>(new Action<CHUNG_TU_CHI_TIET>(this.attach_CHUNG_TU_CHI_TIETs), new Action<CHUNG_TU_CHI_TIET>(this.detach_CHUNG_TU_CHI_TIETs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Chung_Tu", DbType="NVarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Chung_Tu
		{
			get
			{
				return this._Ma_Chung_Tu;
			}
			set
			{
				if ((this._Ma_Chung_Tu != value))
				{
					this.OnMa_Chung_TuChanging(value);
					this.SendPropertyChanging();
					this._Ma_Chung_Tu = value;
					this.SendPropertyChanged("Ma_Chung_Tu");
					this.OnMa_Chung_TuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So", DbType="NVarChar(250)")]
		public string So
		{
			get
			{
				return this._So;
			}
			set
			{
				if ((this._So != value))
				{
					this.OnSoChanging(value);
					this.SendPropertyChanging();
					this._So = value;
					this.SendPropertyChanged("So");
					this.OnSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lien", DbType="NVarChar(250)")]
		public string Lien
		{
			get
			{
				return this._Lien;
			}
			set
			{
				if ((this._Lien != value))
				{
					this.OnLienChanging(value);
					this.SendPropertyChanging();
					this._Lien = value;
					this.SendPropertyChanged("Lien");
					this.OnLienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this.OnNgayChanging(value);
					this.SendPropertyChanging();
					this._Ngay = value;
					this.SendPropertyChanged("Ngay");
					this.OnNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Khach_Hang", DbType="NVarChar(250)")]
		public string Ten_Khach_Hang
		{
			get
			{
				return this._Ten_Khach_Hang;
			}
			set
			{
				if ((this._Ten_Khach_Hang != value))
				{
					this.OnTen_Khach_HangChanging(value);
					this.SendPropertyChanging();
					this._Ten_Khach_Hang = value;
					this.SendPropertyChanged("Ten_Khach_Hang");
					this.OnTen_Khach_HangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_CMND", DbType="NVarChar(250)")]
		public string So_CMND
		{
			get
			{
				return this._So_CMND;
			}
			set
			{
				if ((this._So_CMND != value))
				{
					this.OnSo_CMNDChanging(value);
					this.SendPropertyChanging();
					this._So_CMND = value;
					this.SendPropertyChanged("So_CMND");
					this.OnSo_CMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Cap_CMND", DbType="NVarChar(250)")]
		public string Ngay_Cap_CMND
		{
			get
			{
				return this._Ngay_Cap_CMND;
			}
			set
			{
				if ((this._Ngay_Cap_CMND != value))
				{
					this.OnNgay_Cap_CMNDChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Cap_CMND = value;
					this.SendPropertyChanged("Ngay_Cap_CMND");
					this.OnNgay_Cap_CMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noi_Cap", DbType="NVarChar(250)")]
		public string Noi_Cap
		{
			get
			{
				return this._Noi_Cap;
			}
			set
			{
				if ((this._Noi_Cap != value))
				{
					this.OnNoi_CapChanging(value);
					this.SendPropertyChanging();
					this._Noi_Cap = value;
					this.SendPropertyChanged("Noi_Cap");
					this.OnNoi_CapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Sinh", DbType="NVarChar(250)")]
		public string Ngay_Sinh
		{
			get
			{
				return this._Ngay_Sinh;
			}
			set
			{
				if ((this._Ngay_Sinh != value))
				{
					this.OnNgay_SinhChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Sinh = value;
					this.SendPropertyChanged("Ngay_Sinh");
					this.OnNgay_SinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dia_Chi", DbType="NVarChar(250)")]
		public string Dia_Chi
		{
			get
			{
				return this._Dia_Chi;
			}
			set
			{
				if ((this._Dia_Chi != value))
				{
					this.OnDia_ChiChanging(value);
					this.SendPropertyChanging();
					this._Dia_Chi = value;
					this.SendPropertyChanged("Dia_Chi");
					this.OnDia_ChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Dien_Thoai", DbType="NVarChar(250)")]
		public string So_Dien_Thoai
		{
			get
			{
				return this._So_Dien_Thoai;
			}
			set
			{
				if ((this._So_Dien_Thoai != value))
				{
					this.OnSo_Dien_ThoaiChanging(value);
					this.SendPropertyChanging();
					this._So_Dien_Thoai = value;
					this.SendPropertyChanged("So_Dien_Thoai");
					this.OnSo_Dien_ThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chu_Tiem", DbType="NVarChar(250)")]
		public string Chu_Tiem
		{
			get
			{
				return this._Chu_Tiem;
			}
			set
			{
				if ((this._Chu_Tiem != value))
				{
					this.OnChu_TiemChanging(value);
					this.SendPropertyChanging();
					this._Chu_Tiem = value;
					this.SendPropertyChanged("Chu_Tiem");
					this.OnChu_TiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Tien_Cam", DbType="Money")]
		public System.Nullable<decimal> So_Tien_Cam
		{
			get
			{
				return this._So_Tien_Cam;
			}
			set
			{
				if ((this._So_Tien_Cam != value))
				{
					this.OnSo_Tien_CamChanging(value);
					this.SendPropertyChanging();
					this._So_Tien_Cam = value;
					this.SendPropertyChanged("So_Tien_Cam");
					this.OnSo_Tien_CamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tu_Ngay", DbType="NVarChar(50)")]
		public string Tu_Ngay
		{
			get
			{
				return this._Tu_Ngay;
			}
			set
			{
				if ((this._Tu_Ngay != value))
				{
					this.OnTu_NgayChanging(value);
					this.SendPropertyChanging();
					this._Tu_Ngay = value;
					this.SendPropertyChanged("Tu_Ngay");
					this.OnTu_NgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Den_Ngay", DbType="NVarChar(50)")]
		public string Den_Ngay
		{
			get
			{
				return this._Den_Ngay;
			}
			set
			{
				if ((this._Den_Ngay != value))
				{
					this.OnDen_NgayChanging(value);
					this.SendPropertyChanging();
					this._Den_Ngay = value;
					this.SendPropertyChanged("Den_Ngay");
					this.OnDen_NgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lai_Suat_Ngay", DbType="Money")]
		public System.Nullable<decimal> Lai_Suat_Ngay
		{
			get
			{
				return this._Lai_Suat_Ngay;
			}
			set
			{
				if ((this._Lai_Suat_Ngay != value))
				{
					this.OnLai_Suat_NgayChanging(value);
					this.SendPropertyChanging();
					this._Lai_Suat_Ngay = value;
					this.SendPropertyChanged("Lai_Suat_Ngay");
					this.OnLai_Suat_NgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lai_Suat_Thang", DbType="Money")]
		public System.Nullable<decimal> Lai_Suat_Thang
		{
			get
			{
				return this._Lai_Suat_Thang;
			}
			set
			{
				if ((this._Lai_Suat_Thang != value))
				{
					this.OnLai_Suat_ThangChanging(value);
					this.SendPropertyChanging();
					this._Lai_Suat_Thang = value;
					this.SendPropertyChanged("Lai_Suat_Thang");
					this.OnLai_Suat_ThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghi_Chu", DbType="NVarChar(250)")]
		public string Ghi_Chu
		{
			get
			{
				return this._Ghi_Chu;
			}
			set
			{
				if ((this._Ghi_Chu != value))
				{
					this.OnGhi_ChuChanging(value);
					this.SendPropertyChanging();
					this._Ghi_Chu = value;
					this.SendPropertyChanged("Ghi_Chu");
					this.OnGhi_ChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tien_Lai_Cu", DbType="Money")]
		public System.Nullable<decimal> Tien_Lai_Cu
		{
			get
			{
				return this._Tien_Lai_Cu;
			}
			set
			{
				if ((this._Tien_Lai_Cu != value))
				{
					this.OnTien_Lai_CuChanging(value);
					this.SendPropertyChanging();
					this._Tien_Lai_Cu = value;
					this.SendPropertyChanged("Tien_Lai_Cu");
					this.OnTien_Lai_CuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chung_Tu_Goc", DbType="NVarChar(250)")]
		public string Chung_Tu_Goc
		{
			get
			{
				return this._Chung_Tu_Goc;
			}
			set
			{
				if ((this._Chung_Tu_Goc != value))
				{
					this.OnChung_Tu_GocChanging(value);
					this.SendPropertyChanging();
					this._Chung_Tu_Goc = value;
					this.SendPropertyChanged("Chung_Tu_Goc");
					this.OnChung_Tu_GocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Da_Lam_Lai_Giay", DbType="Bit")]
		public System.Nullable<bool> Da_Lam_Lai_Giay
		{
			get
			{
				return this._Da_Lam_Lai_Giay;
			}
			set
			{
				if ((this._Da_Lam_Lai_Giay != value))
				{
					this.OnDa_Lam_Lai_GiayChanging(value);
					this.SendPropertyChanging();
					this._Da_Lam_Lai_Giay = value;
					this.SendPropertyChanged("Da_Lam_Lai_Giay");
					this.OnDa_Lam_Lai_GiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Da_Chuoc", DbType="Bit")]
		public System.Nullable<bool> Da_Chuoc
		{
			get
			{
				return this._Da_Chuoc;
			}
			set
			{
				if ((this._Da_Chuoc != value))
				{
					this.OnDa_ChuocChanging(value);
					this.SendPropertyChanging();
					this._Da_Chuoc = value;
					this.SendPropertyChanged("Da_Chuoc");
					this.OnDa_ChuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mat_Giay", DbType="Bit")]
		public System.Nullable<bool> Mat_Giay
		{
			get
			{
				return this._Mat_Giay;
			}
			set
			{
				if ((this._Mat_Giay != value))
				{
					this.OnMat_GiayChanging(value);
					this.SendPropertyChanging();
					this._Mat_Giay = value;
					this.SendPropertyChanged("Mat_Giay");
					this.OnMat_GiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sap_Xep", DbType="BigInt")]
		public System.Nullable<long> Sap_Xep
		{
			get
			{
				return this._Sap_Xep;
			}
			set
			{
				if ((this._Sap_Xep != value))
				{
					this.OnSap_XepChanging(value);
					this.SendPropertyChanging();
					this._Sap_Xep = value;
					this.SendPropertyChanged("Sap_Xep");
					this.OnSap_XepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUNG_TU_CHUNG_TU_CHI_TIET", Storage="_CHUNG_TU_CHI_TIETs", ThisKey="Ma_Chung_Tu", OtherKey="Ma_Chung_Tu")]
		public EntitySet<CHUNG_TU_CHI_TIET> CHUNG_TU_CHI_TIETs
		{
			get
			{
				return this._CHUNG_TU_CHI_TIETs;
			}
			set
			{
				this._CHUNG_TU_CHI_TIETs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHUNG_TU_CHI_TIETs(CHUNG_TU_CHI_TIET entity)
		{
			this.SendPropertyChanging();
			entity.CHUNG_TU = this;
		}
		
		private void detach_CHUNG_TU_CHI_TIETs(CHUNG_TU_CHI_TIET entity)
		{
			this.SendPropertyChanging();
			entity.CHUNG_TU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUNG_TU_THU_CHI")]
	public partial class CHUNG_TU_THU_CHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma;
		
		private System.DateTime _Ngay;
		
		private System.Nullable<System.DateTime> _Ngay_Ghi_So;
		
		private string _Ma_Chung_Tu_Cam_Do;
		
		private System.Nullable<decimal> _So_Tien_Cam;
		
		private System.Nullable<decimal> _Tien_Lai;
		
		private System.Nullable<decimal> _So_Tien_Thu;
		
		private System.Nullable<decimal> _So_Tien_Chi;
		
		private System.Nullable<decimal> _Tien_Lai_Cu;
		
		private string _Loai;
		
		private string _Ma_Phan_Loai;
		
		private string _Phan_Loai;
		
		private string _Ten_Loai;
		
		private string _Ghi_Chu;
		
		private System.Nullable<long> _Sap_Xep;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChanging(string value);
    partial void OnMaChanged();
    partial void OnNgayChanging(System.DateTime value);
    partial void OnNgayChanged();
    partial void OnNgay_Ghi_SoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_Ghi_SoChanged();
    partial void OnMa_Chung_Tu_Cam_DoChanging(string value);
    partial void OnMa_Chung_Tu_Cam_DoChanged();
    partial void OnSo_Tien_CamChanging(System.Nullable<decimal> value);
    partial void OnSo_Tien_CamChanged();
    partial void OnTien_LaiChanging(System.Nullable<decimal> value);
    partial void OnTien_LaiChanged();
    partial void OnSo_Tien_ThuChanging(System.Nullable<decimal> value);
    partial void OnSo_Tien_ThuChanged();
    partial void OnSo_Tien_ChiChanging(System.Nullable<decimal> value);
    partial void OnSo_Tien_ChiChanged();
    partial void OnTien_Lai_CuChanging(System.Nullable<decimal> value);
    partial void OnTien_Lai_CuChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnMa_Phan_LoaiChanging(string value);
    partial void OnMa_Phan_LoaiChanged();
    partial void OnPhan_LoaiChanging(string value);
    partial void OnPhan_LoaiChanged();
    partial void OnTen_LoaiChanging(string value);
    partial void OnTen_LoaiChanged();
    partial void OnGhi_ChuChanging(string value);
    partial void OnGhi_ChuChanged();
    partial void OnSap_XepChanging(System.Nullable<long> value);
    partial void OnSap_XepChanged();
    #endregion
		
		public CHUNG_TU_THU_CHI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma", DbType="NVarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma
		{
			get
			{
				return this._Ma;
			}
			set
			{
				if ((this._Ma != value))
				{
					this.OnMaChanging(value);
					this.SendPropertyChanging();
					this._Ma = value;
					this.SendPropertyChanged("Ma");
					this.OnMaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="DateTime NOT NULL")]
		public System.DateTime Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this.OnNgayChanging(value);
					this.SendPropertyChanging();
					this._Ngay = value;
					this.SendPropertyChanged("Ngay");
					this.OnNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Ghi_So", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_Ghi_So
		{
			get
			{
				return this._Ngay_Ghi_So;
			}
			set
			{
				if ((this._Ngay_Ghi_So != value))
				{
					this.OnNgay_Ghi_SoChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Ghi_So = value;
					this.SendPropertyChanged("Ngay_Ghi_So");
					this.OnNgay_Ghi_SoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Chung_Tu_Cam_Do", DbType="NVarChar(250)")]
		public string Ma_Chung_Tu_Cam_Do
		{
			get
			{
				return this._Ma_Chung_Tu_Cam_Do;
			}
			set
			{
				if ((this._Ma_Chung_Tu_Cam_Do != value))
				{
					this.OnMa_Chung_Tu_Cam_DoChanging(value);
					this.SendPropertyChanging();
					this._Ma_Chung_Tu_Cam_Do = value;
					this.SendPropertyChanged("Ma_Chung_Tu_Cam_Do");
					this.OnMa_Chung_Tu_Cam_DoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Tien_Cam", DbType="Money")]
		public System.Nullable<decimal> So_Tien_Cam
		{
			get
			{
				return this._So_Tien_Cam;
			}
			set
			{
				if ((this._So_Tien_Cam != value))
				{
					this.OnSo_Tien_CamChanging(value);
					this.SendPropertyChanging();
					this._So_Tien_Cam = value;
					this.SendPropertyChanged("So_Tien_Cam");
					this.OnSo_Tien_CamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tien_Lai", DbType="Money")]
		public System.Nullable<decimal> Tien_Lai
		{
			get
			{
				return this._Tien_Lai;
			}
			set
			{
				if ((this._Tien_Lai != value))
				{
					this.OnTien_LaiChanging(value);
					this.SendPropertyChanging();
					this._Tien_Lai = value;
					this.SendPropertyChanged("Tien_Lai");
					this.OnTien_LaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Tien_Thu", DbType="Money")]
		public System.Nullable<decimal> So_Tien_Thu
		{
			get
			{
				return this._So_Tien_Thu;
			}
			set
			{
				if ((this._So_Tien_Thu != value))
				{
					this.OnSo_Tien_ThuChanging(value);
					this.SendPropertyChanging();
					this._So_Tien_Thu = value;
					this.SendPropertyChanged("So_Tien_Thu");
					this.OnSo_Tien_ThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Tien_Chi", DbType="Money")]
		public System.Nullable<decimal> So_Tien_Chi
		{
			get
			{
				return this._So_Tien_Chi;
			}
			set
			{
				if ((this._So_Tien_Chi != value))
				{
					this.OnSo_Tien_ChiChanging(value);
					this.SendPropertyChanging();
					this._So_Tien_Chi = value;
					this.SendPropertyChanged("So_Tien_Chi");
					this.OnSo_Tien_ChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tien_Lai_Cu", DbType="Money")]
		public System.Nullable<decimal> Tien_Lai_Cu
		{
			get
			{
				return this._Tien_Lai_Cu;
			}
			set
			{
				if ((this._Tien_Lai_Cu != value))
				{
					this.OnTien_Lai_CuChanging(value);
					this.SendPropertyChanging();
					this._Tien_Lai_Cu = value;
					this.SendPropertyChanged("Tien_Lai_Cu");
					this.OnTien_Lai_CuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(50)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Phan_Loai", DbType="VarChar(50)")]
		public string Ma_Phan_Loai
		{
			get
			{
				return this._Ma_Phan_Loai;
			}
			set
			{
				if ((this._Ma_Phan_Loai != value))
				{
					this.OnMa_Phan_LoaiChanging(value);
					this.SendPropertyChanging();
					this._Ma_Phan_Loai = value;
					this.SendPropertyChanged("Ma_Phan_Loai");
					this.OnMa_Phan_LoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phan_Loai", DbType="NVarChar(50)")]
		public string Phan_Loai
		{
			get
			{
				return this._Phan_Loai;
			}
			set
			{
				if ((this._Phan_Loai != value))
				{
					this.OnPhan_LoaiChanging(value);
					this.SendPropertyChanging();
					this._Phan_Loai = value;
					this.SendPropertyChanged("Phan_Loai");
					this.OnPhan_LoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Loai", DbType="NVarChar(250)")]
		public string Ten_Loai
		{
			get
			{
				return this._Ten_Loai;
			}
			set
			{
				if ((this._Ten_Loai != value))
				{
					this.OnTen_LoaiChanging(value);
					this.SendPropertyChanging();
					this._Ten_Loai = value;
					this.SendPropertyChanged("Ten_Loai");
					this.OnTen_LoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghi_Chu", DbType="NVarChar(250)")]
		public string Ghi_Chu
		{
			get
			{
				return this._Ghi_Chu;
			}
			set
			{
				if ((this._Ghi_Chu != value))
				{
					this.OnGhi_ChuChanging(value);
					this.SendPropertyChanging();
					this._Ghi_Chu = value;
					this.SendPropertyChanged("Ghi_Chu");
					this.OnGhi_ChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sap_Xep", DbType="BigInt")]
		public System.Nullable<long> Sap_Xep
		{
			get
			{
				return this._Sap_Xep;
			}
			set
			{
				if ((this._Sap_Xep != value))
				{
					this.OnSap_XepChanging(value);
					this.SendPropertyChanging();
					this._Sap_Xep = value;
					this.SendPropertyChanged("Sap_Xep");
					this.OnSap_XepChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
